version: '3'
services:
  ner:
    image: linhdpostdata/hismetag:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: on-failure
  apidev:
    image: linhdpostdata/poetrylab-api:dev
    environment:
    - NER_URI=http://ner:8080/api/rest/process/text
    - NER_HEALTH_URI=http://ner:8080/api/
    - "WORKERS=${API_WORKERS:-4}"
    - "TIMEOUT=${API_TIMEOUT:-120}"
    - "PORT=${API_PORT:-5006}"
    expose:
      - "5006"
    ports:
      - "${API_PORT:-5006}:5006"
  api:
    image: linhdpostdata/poetrylab-api
    environment:
    - NER_URI=http://ner:8080/api/rest/process/text
    - NER_HEALTH_URI=http://ner:8080/api/
    - "WORKERS=${API_WORKERS:-4}"
    - "TIMEOUT=${API_TIMEOUT:-120}"
    - "PORT=${API_PORT:-5004}"
    expose:
      - "5004"
    ports:
      - "${API_PORT:-5004}:5004"

  web:
    image: linhdpostdata/poetrylabv3:latest
    environment:
    - API_HOST=evi.linhd.uned.es
    - "API_PORT=${API_PORT:-5004}"
    - REACT_APP_API_ROOT=http://evi.linhd.uned.es:5004
    ports:
      - "8081:80"
    expose:
      - "8081"
